# Generated by Django 5.1.2 on 2024-11-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0002_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
